# Generated by Django 6.1 on 2026-08-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PecaAnatomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('total_frames', models.PositiveIntegerField(default=24, help_text='Total de fotos na volta 360°')),
            ],
            options={
                'verbose_name': 'Peça Anatômica',
                'verbose_name_plural': 'Peças Anatômicas',
            },
        ),
        migrations.CreateModel(
            name='SistemaAnatomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sistema Anatômico',
                'verbose_name_plural': 'Sistemas Anatômicos',
            },
        ),
        migrations.CreateModel(
            name='FramePeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_frame', models.PositiveIntegerField(help_text='Índice da imagem (ex: 0 a 23)')),
                ('imagem', models.ImageField(upload_to='pecas_360/')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.pecaanatomica')),
            ],
            options={
                'verbose_name': 'Frame da Peça',
                'verbose_name_plural': 'Frames da Peça',
                'ordering': ['numero_frame'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaEstrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_alvo', models.PositiveIntegerField(help_text='Índice do frame em que a seta deve apontar')),
                ('posicao_x', models.FloatField(help_text='Posição horizontal da seta em % (0 a 100)')),
                ('posicao_y', models.FloatField(help_text='Posição vertical da seta em % (0 a 100)')),
                ('resposta_correta', models.CharField(help_text='Nome canônico da estrutura (ex: Foramen magnum)', max_length=150)),
                ('sinonimos', models.TextField(blank=True, help_text='Sinônimos aceitos separados por vírgula')),
                ('opcao_a', models.CharField(help_text='Alternativa 1', max_length=150)),
                ('opcao_b', models.CharField(help_text='Alternativa 2', max_length=150)),
                ('opcao_c', models.CharField(help_text='Alternativa 3', max_length=150)),
                ('opcao_d', models.CharField(help_text='Alternativa 4', max_length=150)),
                ('pontos_recall', models.IntegerField(default=20, help_text='Pontos por resposta aberta direta')),
                ('pontos_multipla_escolha', models.IntegerField(default=10, help_text='Pontos por escolha de alternativas')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='api.pecaanatomica')),
            ],
            options={
                'verbose_name': 'Pergunta / Estrutura',
                'verbose_name_plural': 'Perguntas / Estruturas',
            },
        ),
        migrations.AddField(
            model_name='pecaanatomica',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='api.sistemaanatomico'),
        ),
    ]
