# Generated by Django 6.1 on 2026-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecaanatomica',
            name='arquivo_3d',
            field=models.FileField(blank=True, help_text='Arquivo .glb ou .gltf', null=True, upload_to='pecas_3d/'),
        ),
        migrations.AlterField(
            model_name='pecaanatomica',
            name='total_frames',
            field=models.PositiveIntegerField(blank=True, default=24, null=True),
        ),
    ]
