# Generated by Django 5.2.17 on 2026-09-30 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_images_and_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageannotation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='text_es',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='category',
            field=models.CharField(choices=[('skeletal', 'Esquelético'), ('muscular', 'Muscular'), ('digestive', 'Digestório'), ('respiratory', 'Respiratório'), ('circulatory', 'Circulatório')], default='skeletal', max_length=24),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title_es',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='use_ollama',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=12)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveBigIntegerField()),
                ('category', models.CharField(max_length=24)),
                ('correct_text', models.CharField(max_length=500)),
                ('correct_text_es', models.CharField(blank=True, max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('used_open_answer', models.BooleanField()),
                ('correct', models.BooleanField()),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='api.imageannotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
