import type { Question } from './types';

export const questions: Question[] = [
  // SKELETAL
  {
    id: 'sk1',
    system: 'skeletal',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Vista lateral',
    imageAlt_es: 'Perro - Vista lateral',
    marker: { x: 48, y: 58 },
    correct_pt: 'Fêmur',
    correct_es: 'Fémur',
    options_pt: ['Fêmur', 'Tíbia', 'Úmero', 'Fíbula'],
    options_es: ['Fémur', 'Tibia', 'Húmero', 'Fíbula'],
  },
  {
    id: 'sk2',
    system: 'skeletal',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Região torácica',
    imageAlt_es: 'Perro - Región torácica',
    marker: { x: 38, y: 40 },
    correct_pt: 'Escápula',
    correct_es: 'Escápula',
    options_pt: ['Escápula', 'Costela', 'Esterno', 'Clavícula'],
    options_es: ['Escápula', 'Costilla', 'Esternón', 'Clavícula'],
  },
  {
    id: 'sk3',
    system: 'skeletal',
    imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Gato - Vista lateral',
    imageAlt_es: 'Gato - Vista lateral',
    marker: { x: 55, y: 35 },
    correct_pt: 'Vértebra torácica',
    correct_es: 'Vértebra torácica',
    options_pt: ['Vértebra torácica', 'Vértebra lombar', 'Sacro', 'Costela'],
    options_es: ['Vértebra torácica', 'Vértebra lumbar', 'Sacro', 'Costilla'],
  },
  {
    id: 'sk4',
    system: 'skeletal',
    imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Membro anterior',
    imageAlt_es: 'Perro - Miembro anterior',
    marker: { x: 42, y: 52 },
    correct_pt: 'Úmero',
    correct_es: 'Húmero',
    options_pt: ['Úmero', 'Rádio', 'Ulna', 'Carpo'],
    options_es: ['Húmero', 'Radio', 'Ulna', 'Carpo'],
  },
  {
    id: 'sk5',
    system: 'skeletal',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Região pélvica',
    imageAlt_es: 'Perro - Región pélvica',
    marker: { x: 60, y: 55 },
    correct_pt: 'Pelve',
    correct_es: 'Pelvis',
    options_pt: ['Pelve', 'Sacro', 'Fêmur', 'Ísquio'],
    options_es: ['Pelvis', 'Sacro', 'Fémur', 'Isquion'],
  },

  // MUSCULAR
  {
    id: 'mu1',
    system: 'muscular',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Musculatura dorsal',
    imageAlt_es: 'Perro - Musculatura dorsal',
    marker: { x: 35, y: 28 },
    correct_pt: 'Músculo trapézio',
    correct_es: 'Músculo trapecio',
    options_pt: ['Músculo trapézio', 'Músculo deltóide', 'Músculo rombóide', 'Músculo latíssimo'],
    options_es: ['Músculo trapecio', 'Músculo deltoides', 'Músculo romboides', 'Músculo latísimo'],
  },
  {
    id: 'mu2',
    system: 'muscular',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Musculatura do membro posterior',
    imageAlt_es: 'Perro - Musculatura del miembro posterior',
    marker: { x: 50, y: 65 },
    correct_pt: 'Músculo gastrocnêmio',
    correct_es: 'Músculo gastrocnemio',
    options_pt: ['Músculo gastrocnêmio', 'Músculo sóleo', 'Músculo tibial', 'Músculo fibular'],
    options_es: ['Músculo gastrocnemio', 'Músculo sóleo', 'Músculo tibial', 'Músculo fibular'],
  },
  {
    id: 'mu3',
    system: 'muscular',
    imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Gato - Musculatura abdominal',
    imageAlt_es: 'Gato - Musculatura abdominal',
    marker: { x: 48, y: 55 },
    correct_pt: 'Músculo reto abdominal',
    correct_es: 'Músculo recto abdominal',
    options_pt: ['Músculo reto abdominal', 'Músculo oblíquo externo', 'Músculo transverso', 'Diafragma'],
    options_es: ['Músculo recto abdominal', 'Músculo oblicuo externo', 'Músculo transverso', 'Diafragma'],
  },
  {
    id: 'mu4',
    system: 'muscular',
    imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Musculatura torácica',
    imageAlt_es: 'Perro - Musculatura torácica',
    marker: { x: 40, y: 45 },
    correct_pt: 'Diafragma',
    correct_es: 'Diafragma',
    options_pt: ['Diafragma', 'Músculo intercostal', 'Músculo peitoral', 'Músculo serrátil'],
    options_es: ['Diafragma', 'Músculo intercostal', 'Músculo pectoral', 'Músculo serrato'],
  },
  {
    id: 'mu5',
    system: 'muscular',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Musculatura do membro anterior',
    imageAlt_es: 'Perro - Musculatura del miembro anterior',
    marker: { x: 38, y: 48 },
    correct_pt: 'Músculo bíceps braquial',
    correct_es: 'Músculo bíceps braquial',
    options_pt: ['Músculo bíceps braquial', 'Músculo tríceps braquial', 'Músculo braquial', 'Músculo supinador'],
    options_es: ['Músculo bíceps braquial', 'Músculo tríceps braquial', 'Músculo braquial', 'Músculo supinador'],
  },

  // DIGESTIVE
  {
    id: 'di1',
    system: 'digestive',
    imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Cavidade abdominal',
    imageAlt_es: 'Perro - Cavidad abdominal',
    marker: { x: 42, y: 48 },
    correct_pt: 'Estômago',
    correct_es: 'Estómago',
    options_pt: ['Estômago', 'Intestino delgado', 'Baço', 'Pâncreas'],
    options_es: ['Estómago', 'Intestino delgado', 'Bazo', 'Páncreas'],
  },
  {
    id: 'di2',
    system: 'digestive',
    imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Gato - Região hepática',
    imageAlt_es: 'Gato - Región hepática',
    marker: { x: 45, y: 42 },
    correct_pt: 'Fígado',
    correct_es: 'Hígado',
    options_pt: ['Fígado', 'Vesícula biliar', 'Pâncreas', 'Baço'],
    options_es: ['Hígado', 'Vesícula biliar', 'Páncreas', 'Bazo'],
  },
  {
    id: 'di3',
    system: 'digestive',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Intestino delgado',
    imageAlt_es: 'Perro - Intestino delgado',
    marker: { x: 50, y: 56 },
    correct_pt: 'Intestino delgado',
    correct_es: 'Intestino delgado',
    options_pt: ['Intestino delgado', 'Cólon', 'Ceco', 'Reto'],
    options_es: ['Intestino delgado', 'Colon', 'Ciego', 'Recto'],
  },
  {
    id: 'di4',
    system: 'digestive',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Esôfago',
    imageAlt_es: 'Perro - Esófago',
    marker: { x: 35, y: 30 },
    correct_pt: 'Esôfago',
    correct_es: 'Esófago',
    options_pt: ['Esôfago', 'Traqueia', 'Aorta', 'Veia cava'],
    options_es: ['Esófago', 'Tráquea', 'Aorta', 'Vena cava'],
  },
  {
    id: 'di5',
    system: 'digestive',
    imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Gato - Pâncreas',
    imageAlt_es: 'Gato - Páncreas',
    marker: { x: 46, y: 50 },
    correct_pt: 'Pâncreas',
    correct_es: 'Páncreas',
    options_pt: ['Pâncreas', 'Fígado', 'Baço', 'Rim'],
    options_es: ['Páncreas', 'Hígado', 'Bazo', 'Riñón'],
  },

  // RESPIRATORY
  {
    id: 're1',
    system: 'respiratory',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Traqueia',
    imageAlt_es: 'Perro - Tráquea',
    marker: { x: 40, y: 28 },
    correct_pt: 'Traqueia',
    correct_es: 'Tráquea',
    options_pt: ['Traqueia', 'Esôfago', 'Laringe', 'Brônquio'],
    options_es: ['Tráquea', 'Esófago', 'Laringe', 'Bronquio'],
  },
  {
    id: 're2',
    system: 'respiratory',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Pulmão',
    imageAlt_es: 'Perro - Pulmón',
    marker: { x: 38, y: 40 },
    correct_pt: 'Pulmão',
    correct_es: 'Pulmón',
    options_pt: ['Pulmão', 'Coração', 'Timo', 'Diafragma'],
    options_es: ['Pulmón', 'Corazón', 'Timo', 'Diafragma'],
  },
  {
    id: 're3',
    system: 'respiratory',
    imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Gato - Laringe',
    imageAlt_es: 'Gato - Laringe',
    marker: { x: 45, y: 22 },
    correct_pt: 'Laringe',
    correct_es: 'Laringe',
    options_pt: ['Laringe', 'Faringe', 'Traqueia', 'Epiglote'],
    options_es: ['Laringe', 'Faringe', 'Tráquea', 'Epiglotis'],
  },
  {
    id: 're4',
    system: 'respiratory',
    imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Brônquio',
    imageAlt_es: 'Perro - Bronquio',
    marker: { x: 44, y: 38 },
    correct_pt: 'Brônquio',
    correct_es: 'Bronquio',
    options_pt: ['Brônquio', 'Traqueia', 'Alvéolo', 'Pleura'],
    options_es: ['Bronquio', 'Tráquea', 'Alvéolo', 'Pleura'],
  },
  {
    id: 're5',
    system: 'respiratory',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Diafragma respiratório',
    imageAlt_es: 'Perro - Diafragma respiratorio',
    marker: { x: 50, y: 52 },
    correct_pt: 'Diafragma',
    correct_es: 'Diafragma',
    options_pt: ['Diafragma', 'Peritônio', 'Pleura', 'Pericárdio'],
    options_es: ['Diafragma', 'Peritoneo', 'Pleura', 'Pericardio'],
  },

  // CIRCULATORY
  {
    id: 'ci1',
    system: 'circulatory',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Coração',
    imageAlt_es: 'Perro - Corazón',
    marker: { x: 42, y: 42 },
    correct_pt: 'Coração',
    correct_es: 'Corazón',
    options_pt: ['Coração', 'Pulmão', 'Timo', 'Baço'],
    options_es: ['Corazón', 'Pulmón', 'Timo', 'Bazo'],
  },
  {
    id: 'ci2',
    system: 'circulatory',
    imageUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Gato - Aorta',
    imageAlt_es: 'Gato - Aorta',
    marker: { x: 46, y: 38 },
    correct_pt: 'Aorta',
    correct_es: 'Aorta',
    options_pt: ['Aorta', 'Veia cava', 'Artéria pulmonar', 'Veia jugular'],
    options_es: ['Aorta', 'Vena cava', 'Arteria pulmonar', 'Vena yugular'],
  },
  {
    id: 'ci3',
    system: 'circulatory',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Veia cava',
    imageAlt_es: 'Perro - Vena cava',
    marker: { x: 50, y: 44 },
    correct_pt: 'Veia cava caudal',
    correct_es: 'Vena cava caudal',
    options_pt: ['Veia cava caudal', 'Aorta', 'Veia portal', 'Artéria femoral'],
    options_es: ['Vena cava caudal', 'Aorta', 'Vena portal', 'Arteria femoral'],
  },
  {
    id: 'ci4',
    system: 'circulatory',
    imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Artéria pulmonar',
    imageAlt_es: 'Perro - Arteria pulmonar',
    marker: { x: 44, y: 40 },
    correct_pt: 'Artéria pulmonar',
    correct_es: 'Arteria pulmonar',
    options_pt: ['Artéria pulmonar', 'Veia pulmonar', 'Aorta', 'Veia cava'],
    options_es: ['Arteria pulmonar', 'Vena pulmonar', 'Aorta', 'Vena cava'],
  },
  {
    id: 'ci5',
    system: 'circulatory',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=620&h=460&fit=crop&auto=format',
    imageAlt_pt: 'Cão - Ventrículo esquerdo',
    imageAlt_es: 'Perro - Ventrículo izquierdo',
    marker: { x: 45, y: 46 },
    correct_pt: 'Ventrículo esquerdo',
    correct_es: 'Ventrículo izquierdo',
    options_pt: ['Ventrículo esquerdo', 'Ventrículo direito', 'Átrio esquerdo', 'Átrio direito'],
    options_es: ['Ventrículo izquierdo', 'Ventrículo derecho', 'Atrio izquierdo', 'Atrio derecho'],
  },
];

export function getQuestions(system: string, count = 10): Question[] {
  const pool = system === 'all' ? questions : questions.filter(q => q.system === system);
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
